// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TP24.Data;

#nullable disable

namespace TP24.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230823151904_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TP24.Models.ReceivablePayload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Cancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("ClosedDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DebtorAddress1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DebtorAddress2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DebtorCountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DebtorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DebtorReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DebtorRegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DebtorState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DebtorTown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DebtorZip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DueDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IssueDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OpeningValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PaidValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Receivables");
                });
#pragma warning restore 612, 618
        }
    }
}
